# Generated by Django 4.2.2 on 2023-06-19 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('password', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('user', 'user'), ('manager', 'manager')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='loan_amount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('loan_due_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('pay_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='pending', max_length=10)),
                ('manager_comment', models.TextField()),
                ('loan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
